import type { Metadata } from "next";
import "../styles/global.css";
import { Header } from "../components/shared/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className='h-full antialiased'
    >
      <body className="min-h-full flex flex-col">{children}
        <Header/>
      </body>
    </html>
  );
}
